# change the followings to match your Github username and repo name
baseurl: "/aboutme" # the name of your github repo
url: "https://lauragarcia.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "© Laura García Perrín"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Code Couture
author-bio: Stylish Solutions in Data Science, AI, and Cyber Security  # change to false to hide
author-image: unnamed.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Projetcs
  permalink: projects
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/pperrinn
linkedin: https://www.linkedin.com/in/laura-g-2a067528b/
medium: false
google-scholar: false
email: false
# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
